/*
* generated by Xtext
*/
package com.lowcoupling.mdpm.lng.resources;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class ResourcesUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return com.lowcoupling.mdpm.lng.resources.ui.internal.ResourcesActivator.getInstance().getInjector("com.lowcoupling.mdpm.lng.resources.Resources");
	}
	
}
