/*
* generated by Xtext
*/
package com.lowcoupling.mdpm.lng.resources.ui.contentassist;

/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class ResourcesProposalProvider extends AbstractResourcesProposalProvider {

}
