/*
* generated by Xtext
*/
package com.lowcoupling.mdpm.lng.pbs.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import com.lowcoupling.mdpm.lng.pbs.services.PBSGrammarAccess;

public class PBSParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private PBSGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_SL_COMMENT");
	}
	
	@Override
	protected com.lowcoupling.mdpm.lng.pbs.parser.antlr.internal.InternalPBSParser createParser(XtextTokenStream stream) {
		return new com.lowcoupling.mdpm.lng.pbs.parser.antlr.internal.InternalPBSParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "PBS";
	}
	
	public PBSGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(PBSGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
