/*
* generated by Xtext
*/
package com.lowcoupling.mdpm.lng.plan.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.common.services.TerminalsGrammarAccess;

@Singleton
public class PlanGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class ProgramElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Program");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Assignment cDescriptionAssignment_0_0 = (Assignment)cGroup_0.eContents().get(0);
		private final RuleCall cDescriptionML_COMMENTTerminalRuleCall_0_0_0 = (RuleCall)cDescriptionAssignment_0_0.eContents().get(0);
		private final Group cGroup_0_1 = (Group)cGroup_0.eContents().get(1);
		private final Keyword cProgramKeyword_0_1_0 = (Keyword)cGroup_0_1.eContents().get(0);
		private final Assignment cNameAssignment_0_1_1 = (Assignment)cGroup_0_1.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_0_1_1_0 = (RuleCall)cNameAssignment_0_1_1.eContents().get(0);
		private final RuleCall cOPENCURLYTerminalRuleCall_0_1_2 = (RuleCall)cGroup_0_1.eContents().get(2);
		private final Group cGroup_0_1_3 = (Group)cGroup_0_1.eContents().get(3);
		private final Keyword cNameKeyword_0_1_3_0 = (Keyword)cGroup_0_1_3.eContents().get(0);
		private final Assignment cLongNameAssignment_0_1_3_1 = (Assignment)cGroup_0_1_3.eContents().get(1);
		private final RuleCall cLongNameSTRINGTerminalRuleCall_0_1_3_1_0 = (RuleCall)cLongNameAssignment_0_1_3_1.eContents().get(0);
		private final RuleCall cENDLINEParserRuleCall_0_1_3_2 = (RuleCall)cGroup_0_1_3.eContents().get(2);
		private final Group cGroup_0_1_4 = (Group)cGroup_0_1.eContents().get(4);
		private final Assignment cPlansAssignment_0_1_4_0 = (Assignment)cGroup_0_1_4.eContents().get(0);
		private final RuleCall cPlansPlanImportParserRuleCall_0_1_4_0_0 = (RuleCall)cPlansAssignment_0_1_4_0.eContents().get(0);
		private final RuleCall cENDLINEParserRuleCall_0_1_4_1 = (RuleCall)cGroup_0_1_4.eContents().get(1);
		private final Group cGroup_0_1_5 = (Group)cGroup_0_1.eContents().get(5);
		private final Keyword cProjectKeyword_0_1_5_0 = (Keyword)cGroup_0_1_5.eContents().get(0);
		private final Assignment cReferencedProjectsAssignment_0_1_5_1 = (Assignment)cGroup_0_1_5.eContents().get(1);
		private final CrossReference cReferencedProjectsProjectCrossReference_0_1_5_1_0 = (CrossReference)cReferencedProjectsAssignment_0_1_5_1.eContents().get(0);
		private final RuleCall cReferencedProjectsProjectQualifiedNameParserRuleCall_0_1_5_1_0_1 = (RuleCall)cReferencedProjectsProjectCrossReference_0_1_5_1_0.eContents().get(1);
		private final RuleCall cENDLINEParserRuleCall_0_1_5_2 = (RuleCall)cGroup_0_1_5.eContents().get(2);
		private final Assignment cProjectsAssignment_0_1_6 = (Assignment)cGroup_0_1.eContents().get(6);
		private final RuleCall cProjectsProjectParserRuleCall_0_1_6_0 = (RuleCall)cProjectsAssignment_0_1_6.eContents().get(0);
		private final RuleCall cCLOSEDCURLYTerminalRuleCall_0_1_7 = (RuleCall)cGroup_0_1.eContents().get(7);
		private final Assignment cProjectsAssignment_1 = (Assignment)cAlternatives.eContents().get(1);
		private final RuleCall cProjectsProjectParserRuleCall_1_0 = (RuleCall)cProjectsAssignment_1.eContents().get(0);
		
		//Program:
		//	description=ML_COMMENT? ("Program" name=ID OPENCURLY ("name" longName=STRING ENDLINE)? (plans+=PlanImport ENDLINE)*
		//	("project" referencedProjects+=[Project|QualifiedName] ENDLINE)* projects+=Project* CLOSEDCURLY) | projects+=Project;
		public ParserRule getRule() { return rule; }

		//description=ML_COMMENT? ("Program" name=ID OPENCURLY ("name" longName=STRING ENDLINE)? (plans+=PlanImport ENDLINE)*
		//("project" referencedProjects+=[Project|QualifiedName] ENDLINE)* projects+=Project* CLOSEDCURLY) | projects+=Project
		public Alternatives getAlternatives() { return cAlternatives; }

		//description=ML_COMMENT? ("Program" name=ID OPENCURLY ("name" longName=STRING ENDLINE)? (plans+=PlanImport ENDLINE)*
		//("project" referencedProjects+=[Project|QualifiedName] ENDLINE)* projects+=Project* CLOSEDCURLY)
		public Group getGroup_0() { return cGroup_0; }

		//description=ML_COMMENT?
		public Assignment getDescriptionAssignment_0_0() { return cDescriptionAssignment_0_0; }

		//ML_COMMENT
		public RuleCall getDescriptionML_COMMENTTerminalRuleCall_0_0_0() { return cDescriptionML_COMMENTTerminalRuleCall_0_0_0; }

		//"Program" name=ID OPENCURLY ("name" longName=STRING ENDLINE)? (plans+=PlanImport ENDLINE)* ("project"
		//referencedProjects+=[Project|QualifiedName] ENDLINE)* projects+=Project* CLOSEDCURLY
		public Group getGroup_0_1() { return cGroup_0_1; }

		//"Program"
		public Keyword getProgramKeyword_0_1_0() { return cProgramKeyword_0_1_0; }

		//name=ID
		public Assignment getNameAssignment_0_1_1() { return cNameAssignment_0_1_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_0_1_1_0() { return cNameIDTerminalRuleCall_0_1_1_0; }

		//OPENCURLY
		public RuleCall getOPENCURLYTerminalRuleCall_0_1_2() { return cOPENCURLYTerminalRuleCall_0_1_2; }

		//("name" longName=STRING ENDLINE)?
		public Group getGroup_0_1_3() { return cGroup_0_1_3; }

		//"name"
		public Keyword getNameKeyword_0_1_3_0() { return cNameKeyword_0_1_3_0; }

		//longName=STRING
		public Assignment getLongNameAssignment_0_1_3_1() { return cLongNameAssignment_0_1_3_1; }

		//STRING
		public RuleCall getLongNameSTRINGTerminalRuleCall_0_1_3_1_0() { return cLongNameSTRINGTerminalRuleCall_0_1_3_1_0; }

		//ENDLINE
		public RuleCall getENDLINEParserRuleCall_0_1_3_2() { return cENDLINEParserRuleCall_0_1_3_2; }

		//(plans+=PlanImport ENDLINE)*
		public Group getGroup_0_1_4() { return cGroup_0_1_4; }

		//plans+=PlanImport
		public Assignment getPlansAssignment_0_1_4_0() { return cPlansAssignment_0_1_4_0; }

		//PlanImport
		public RuleCall getPlansPlanImportParserRuleCall_0_1_4_0_0() { return cPlansPlanImportParserRuleCall_0_1_4_0_0; }

		//ENDLINE
		public RuleCall getENDLINEParserRuleCall_0_1_4_1() { return cENDLINEParserRuleCall_0_1_4_1; }

		//("project" referencedProjects+=[Project|QualifiedName] ENDLINE)*
		public Group getGroup_0_1_5() { return cGroup_0_1_5; }

		//"project"
		public Keyword getProjectKeyword_0_1_5_0() { return cProjectKeyword_0_1_5_0; }

		//referencedProjects+=[Project|QualifiedName]
		public Assignment getReferencedProjectsAssignment_0_1_5_1() { return cReferencedProjectsAssignment_0_1_5_1; }

		//[Project|QualifiedName]
		public CrossReference getReferencedProjectsProjectCrossReference_0_1_5_1_0() { return cReferencedProjectsProjectCrossReference_0_1_5_1_0; }

		//QualifiedName
		public RuleCall getReferencedProjectsProjectQualifiedNameParserRuleCall_0_1_5_1_0_1() { return cReferencedProjectsProjectQualifiedNameParserRuleCall_0_1_5_1_0_1; }

		//ENDLINE
		public RuleCall getENDLINEParserRuleCall_0_1_5_2() { return cENDLINEParserRuleCall_0_1_5_2; }

		//projects+=Project*
		public Assignment getProjectsAssignment_0_1_6() { return cProjectsAssignment_0_1_6; }

		//Project
		public RuleCall getProjectsProjectParserRuleCall_0_1_6_0() { return cProjectsProjectParserRuleCall_0_1_6_0; }

		//CLOSEDCURLY
		public RuleCall getCLOSEDCURLYTerminalRuleCall_0_1_7() { return cCLOSEDCURLYTerminalRuleCall_0_1_7; }

		//projects+=Project
		public Assignment getProjectsAssignment_1() { return cProjectsAssignment_1; }

		//Project
		public RuleCall getProjectsProjectParserRuleCall_1_0() { return cProjectsProjectParserRuleCall_1_0; }
	}

	public class ProjectElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Project");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cDescriptionAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cDescriptionML_COMMENTTerminalRuleCall_0_0 = (RuleCall)cDescriptionAssignment_0.eContents().get(0);
		private final Keyword cProjectKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameIDTerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final RuleCall cOPENCURLYTerminalRuleCall_3 = (RuleCall)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cNameKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cLongNameAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cLongNameSTRINGTerminalRuleCall_4_1_0 = (RuleCall)cLongNameAssignment_4_1.eContents().get(0);
		private final RuleCall cENDLINEParserRuleCall_4_2 = (RuleCall)cGroup_4.eContents().get(2);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Assignment cWbsAssignment_5_0 = (Assignment)cGroup_5.eContents().get(0);
		private final RuleCall cWbsWBSImportParserRuleCall_5_0_0 = (RuleCall)cWbsAssignment_5_0.eContents().get(0);
		private final Keyword cProjectKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cWbsProjectAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final CrossReference cWbsProjectWBSProjectCrossReference_5_2_0 = (CrossReference)cWbsProjectAssignment_5_2.eContents().get(0);
		private final RuleCall cWbsProjectWBSProjectQualifiedNameParserRuleCall_5_2_0_1 = (RuleCall)cWbsProjectWBSProjectCrossReference_5_2_0.eContents().get(1);
		private final RuleCall cENDLINEParserRuleCall_5_3 = (RuleCall)cGroup_5.eContents().get(3);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Assignment cResourcesAssignment_6_0 = (Assignment)cGroup_6.eContents().get(0);
		private final RuleCall cResourcesResourcesImportParserRuleCall_6_0_0 = (RuleCall)cResourcesAssignment_6_0.eContents().get(0);
		private final RuleCall cENDLINEParserRuleCall_6_1 = (RuleCall)cGroup_6.eContents().get(1);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Assignment cPlansAssignment_7_0 = (Assignment)cGroup_7.eContents().get(0);
		private final RuleCall cPlansPlanImportParserRuleCall_7_0_0 = (RuleCall)cPlansAssignment_7_0.eContents().get(0);
		private final RuleCall cENDLINEParserRuleCall_7_1 = (RuleCall)cGroup_7.eContents().get(1);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cAssumptionsKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final RuleCall cOPENCURLYTerminalRuleCall_8_1 = (RuleCall)cGroup_8.eContents().get(1);
		private final Assignment cAssumptionsAssignment_8_2 = (Assignment)cGroup_8.eContents().get(2);
		private final RuleCall cAssumptionsAssumptionParserRuleCall_8_2_0 = (RuleCall)cAssumptionsAssignment_8_2.eContents().get(0);
		private final RuleCall cCLOSEDCURLYTerminalRuleCall_8_3 = (RuleCall)cGroup_8.eContents().get(3);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cConstraintsKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final RuleCall cOPENCURLYTerminalRuleCall_9_1 = (RuleCall)cGroup_9.eContents().get(1);
		private final Assignment cConstraintsAssignment_9_2 = (Assignment)cGroup_9.eContents().get(2);
		private final RuleCall cConstraintsConstraintParserRuleCall_9_2_0 = (RuleCall)cConstraintsAssignment_9_2.eContents().get(0);
		private final RuleCall cCLOSEDCURLYTerminalRuleCall_9_3 = (RuleCall)cGroup_9.eContents().get(3);
		private final Assignment cActivitiesAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final RuleCall cActivitiesActivityElementParserRuleCall_10_0 = (RuleCall)cActivitiesAssignment_10.eContents().get(0);
		private final RuleCall cCLOSEDCURLYTerminalRuleCall_11 = (RuleCall)cGroup.eContents().get(11);
		
		//Project:
		//	description=ML_COMMENT? "Project" name=ID OPENCURLY ("name" longName=STRING ENDLINE)? (wbs=WBSImport "project"
		//	wbsProject=[wbs::WBSProject|QualifiedName] ENDLINE)? (resources=ResourcesImport ENDLINE)? (plans+=PlanImport
		//	ENDLINE)* ("assumptions" OPENCURLY assumptions+=Assumption* CLOSEDCURLY)? ("constraints" OPENCURLY
		//	constraints+=Constraint* CLOSEDCURLY)? activities+=ActivityElement* CLOSEDCURLY;
		public ParserRule getRule() { return rule; }

		//description=ML_COMMENT? "Project" name=ID OPENCURLY ("name" longName=STRING ENDLINE)? (wbs=WBSImport "project"
		//wbsProject=[wbs::WBSProject|QualifiedName] ENDLINE)? (resources=ResourcesImport ENDLINE)? (plans+=PlanImport ENDLINE)*
		//("assumptions" OPENCURLY assumptions+=Assumption* CLOSEDCURLY)? ("constraints" OPENCURLY constraints+=Constraint*
		//CLOSEDCURLY)? activities+=ActivityElement* CLOSEDCURLY
		public Group getGroup() { return cGroup; }

		//description=ML_COMMENT?
		public Assignment getDescriptionAssignment_0() { return cDescriptionAssignment_0; }

		//ML_COMMENT
		public RuleCall getDescriptionML_COMMENTTerminalRuleCall_0_0() { return cDescriptionML_COMMENTTerminalRuleCall_0_0; }

		//"Project"
		public Keyword getProjectKeyword_1() { return cProjectKeyword_1; }

		//name=ID
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_2_0() { return cNameIDTerminalRuleCall_2_0; }

		//OPENCURLY
		public RuleCall getOPENCURLYTerminalRuleCall_3() { return cOPENCURLYTerminalRuleCall_3; }

		//("name" longName=STRING ENDLINE)?
		public Group getGroup_4() { return cGroup_4; }

		//"name"
		public Keyword getNameKeyword_4_0() { return cNameKeyword_4_0; }

		//longName=STRING
		public Assignment getLongNameAssignment_4_1() { return cLongNameAssignment_4_1; }

		//STRING
		public RuleCall getLongNameSTRINGTerminalRuleCall_4_1_0() { return cLongNameSTRINGTerminalRuleCall_4_1_0; }

		//ENDLINE
		public RuleCall getENDLINEParserRuleCall_4_2() { return cENDLINEParserRuleCall_4_2; }

		//(wbs=WBSImport "project" wbsProject=[wbs::WBSProject|QualifiedName] ENDLINE)?
		public Group getGroup_5() { return cGroup_5; }

		//wbs=WBSImport
		public Assignment getWbsAssignment_5_0() { return cWbsAssignment_5_0; }

		//WBSImport
		public RuleCall getWbsWBSImportParserRuleCall_5_0_0() { return cWbsWBSImportParserRuleCall_5_0_0; }

		//"project"
		public Keyword getProjectKeyword_5_1() { return cProjectKeyword_5_1; }

		//wbsProject=[wbs::WBSProject|QualifiedName]
		public Assignment getWbsProjectAssignment_5_2() { return cWbsProjectAssignment_5_2; }

		//[wbs::WBSProject|QualifiedName]
		public CrossReference getWbsProjectWBSProjectCrossReference_5_2_0() { return cWbsProjectWBSProjectCrossReference_5_2_0; }

		//QualifiedName
		public RuleCall getWbsProjectWBSProjectQualifiedNameParserRuleCall_5_2_0_1() { return cWbsProjectWBSProjectQualifiedNameParserRuleCall_5_2_0_1; }

		//ENDLINE
		public RuleCall getENDLINEParserRuleCall_5_3() { return cENDLINEParserRuleCall_5_3; }

		//(resources=ResourcesImport ENDLINE)?
		public Group getGroup_6() { return cGroup_6; }

		//resources=ResourcesImport
		public Assignment getResourcesAssignment_6_0() { return cResourcesAssignment_6_0; }

		//ResourcesImport
		public RuleCall getResourcesResourcesImportParserRuleCall_6_0_0() { return cResourcesResourcesImportParserRuleCall_6_0_0; }

		//ENDLINE
		public RuleCall getENDLINEParserRuleCall_6_1() { return cENDLINEParserRuleCall_6_1; }

		//(plans+=PlanImport ENDLINE)*
		public Group getGroup_7() { return cGroup_7; }

		//plans+=PlanImport
		public Assignment getPlansAssignment_7_0() { return cPlansAssignment_7_0; }

		//PlanImport
		public RuleCall getPlansPlanImportParserRuleCall_7_0_0() { return cPlansPlanImportParserRuleCall_7_0_0; }

		//ENDLINE
		public RuleCall getENDLINEParserRuleCall_7_1() { return cENDLINEParserRuleCall_7_1; }

		//("assumptions" OPENCURLY assumptions+=Assumption* CLOSEDCURLY)?
		public Group getGroup_8() { return cGroup_8; }

		//"assumptions"
		public Keyword getAssumptionsKeyword_8_0() { return cAssumptionsKeyword_8_0; }

		//OPENCURLY
		public RuleCall getOPENCURLYTerminalRuleCall_8_1() { return cOPENCURLYTerminalRuleCall_8_1; }

		//assumptions+=Assumption*
		public Assignment getAssumptionsAssignment_8_2() { return cAssumptionsAssignment_8_2; }

		//Assumption
		public RuleCall getAssumptionsAssumptionParserRuleCall_8_2_0() { return cAssumptionsAssumptionParserRuleCall_8_2_0; }

		//CLOSEDCURLY
		public RuleCall getCLOSEDCURLYTerminalRuleCall_8_3() { return cCLOSEDCURLYTerminalRuleCall_8_3; }

		//("constraints" OPENCURLY constraints+=Constraint* CLOSEDCURLY)?
		public Group getGroup_9() { return cGroup_9; }

		//"constraints"
		public Keyword getConstraintsKeyword_9_0() { return cConstraintsKeyword_9_0; }

		//OPENCURLY
		public RuleCall getOPENCURLYTerminalRuleCall_9_1() { return cOPENCURLYTerminalRuleCall_9_1; }

		//constraints+=Constraint*
		public Assignment getConstraintsAssignment_9_2() { return cConstraintsAssignment_9_2; }

		//Constraint
		public RuleCall getConstraintsConstraintParserRuleCall_9_2_0() { return cConstraintsConstraintParserRuleCall_9_2_0; }

		//CLOSEDCURLY
		public RuleCall getCLOSEDCURLYTerminalRuleCall_9_3() { return cCLOSEDCURLYTerminalRuleCall_9_3; }

		//activities+=ActivityElement*
		public Assignment getActivitiesAssignment_10() { return cActivitiesAssignment_10; }

		//ActivityElement
		public RuleCall getActivitiesActivityElementParserRuleCall_10_0() { return cActivitiesActivityElementParserRuleCall_10_0; }

		//CLOSEDCURLY
		public RuleCall getCLOSEDCURLYTerminalRuleCall_11() { return cCLOSEDCURLYTerminalRuleCall_11; }
	}

	public class AssumptionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Assumption");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cValueAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cValueSTRINGTerminalRuleCall_1_0 = (RuleCall)cValueAssignment_1.eContents().get(0);
		private final RuleCall cENDLINEParserRuleCall_2 = (RuleCall)cGroup.eContents().get(2);
		
		//Assumption:
		//	"-" value=STRING ENDLINE;
		public ParserRule getRule() { return rule; }

		//"-" value=STRING ENDLINE
		public Group getGroup() { return cGroup; }

		//"-"
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }

		//value=STRING
		public Assignment getValueAssignment_1() { return cValueAssignment_1; }

		//STRING
		public RuleCall getValueSTRINGTerminalRuleCall_1_0() { return cValueSTRINGTerminalRuleCall_1_0; }

		//ENDLINE
		public RuleCall getENDLINEParserRuleCall_2() { return cENDLINEParserRuleCall_2; }
	}

	public class ConstraintElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Constraint");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cValueAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cValueSTRINGTerminalRuleCall_1_0 = (RuleCall)cValueAssignment_1.eContents().get(0);
		private final RuleCall cENDLINEParserRuleCall_2 = (RuleCall)cGroup.eContents().get(2);
		
		//Constraint:
		//	"-" value=STRING ENDLINE;
		public ParserRule getRule() { return rule; }

		//"-" value=STRING ENDLINE
		public Group getGroup() { return cGroup; }

		//"-"
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }

		//value=STRING
		public Assignment getValueAssignment_1() { return cValueAssignment_1; }

		//STRING
		public RuleCall getValueSTRINGTerminalRuleCall_1_0() { return cValueSTRINGTerminalRuleCall_1_0; }

		//ENDLINE
		public RuleCall getENDLINEParserRuleCall_2() { return cENDLINEParserRuleCall_2; }
	}

	public class ActivityGroupElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ActivityGroup");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cDescriptionAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cDescriptionML_COMMENTTerminalRuleCall_0_0 = (RuleCall)cDescriptionAssignment_0.eContents().get(0);
		private final Keyword cGroupKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameIDTerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final RuleCall cOPENCURLYTerminalRuleCall_3 = (RuleCall)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cNameKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cLongNameAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cLongNameSTRINGTerminalRuleCall_4_1_0 = (RuleCall)cLongNameAssignment_4_1.eContents().get(0);
		private final RuleCall cENDLINEParserRuleCall_4_2 = (RuleCall)cGroup_4.eContents().get(2);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cWbsActivityKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cWbsActivityAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final CrossReference cWbsActivityWBSActivityCrossReference_5_1_0 = (CrossReference)cWbsActivityAssignment_5_1.eContents().get(0);
		private final RuleCall cWbsActivityWBSActivityQualifiedNameParserRuleCall_5_1_0_1 = (RuleCall)cWbsActivityWBSActivityCrossReference_5_1_0.eContents().get(1);
		private final RuleCall cENDLINEParserRuleCall_5_2 = (RuleCall)cGroup_5.eContents().get(2);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cDependsOnKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cDependenciesAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final CrossReference cDependenciesActivityElementCrossReference_6_1_0 = (CrossReference)cDependenciesAssignment_6_1.eContents().get(0);
		private final RuleCall cDependenciesActivityElementQualifiedNameParserRuleCall_6_1_0_1 = (RuleCall)cDependenciesActivityElementCrossReference_6_1_0.eContents().get(1);
		private final RuleCall cENDLINEParserRuleCall_6_2 = (RuleCall)cGroup_6.eContents().get(2);
		private final Assignment cActivitiesAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cActivitiesActivityElementParserRuleCall_7_0 = (RuleCall)cActivitiesAssignment_7.eContents().get(0);
		private final RuleCall cCLOSEDCURLYTerminalRuleCall_8 = (RuleCall)cGroup.eContents().get(8);
		
		//ActivityGroup:
		//	description=ML_COMMENT? "Group" name=ID OPENCURLY ("name" longName=STRING ENDLINE)? ("wbsActivity"
		//	wbsActivity+=[wbs::WBSActivity|QualifiedName]* ENDLINE)? ("dependsOn" dependencies+=[ActivityElement|QualifiedName]*
		//	ENDLINE)? activities+=ActivityElement* //groups += ActivityGroup*
		//	CLOSEDCURLY;
		public ParserRule getRule() { return rule; }

		//description=ML_COMMENT? "Group" name=ID OPENCURLY ("name" longName=STRING ENDLINE)? ("wbsActivity"
		//wbsActivity+=[wbs::WBSActivity|QualifiedName]* ENDLINE)? ("dependsOn" dependencies+=[ActivityElement|QualifiedName]*
		//ENDLINE)? activities+=ActivityElement* //groups += ActivityGroup*
		//CLOSEDCURLY
		public Group getGroup() { return cGroup; }

		//description=ML_COMMENT?
		public Assignment getDescriptionAssignment_0() { return cDescriptionAssignment_0; }

		//ML_COMMENT
		public RuleCall getDescriptionML_COMMENTTerminalRuleCall_0_0() { return cDescriptionML_COMMENTTerminalRuleCall_0_0; }

		//"Group"
		public Keyword getGroupKeyword_1() { return cGroupKeyword_1; }

		//name=ID
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_2_0() { return cNameIDTerminalRuleCall_2_0; }

		//OPENCURLY
		public RuleCall getOPENCURLYTerminalRuleCall_3() { return cOPENCURLYTerminalRuleCall_3; }

		//("name" longName=STRING ENDLINE)?
		public Group getGroup_4() { return cGroup_4; }

		//"name"
		public Keyword getNameKeyword_4_0() { return cNameKeyword_4_0; }

		//longName=STRING
		public Assignment getLongNameAssignment_4_1() { return cLongNameAssignment_4_1; }

		//STRING
		public RuleCall getLongNameSTRINGTerminalRuleCall_4_1_0() { return cLongNameSTRINGTerminalRuleCall_4_1_0; }

		//ENDLINE
		public RuleCall getENDLINEParserRuleCall_4_2() { return cENDLINEParserRuleCall_4_2; }

		//("wbsActivity" wbsActivity+=[wbs::WBSActivity|QualifiedName]* ENDLINE)?
		public Group getGroup_5() { return cGroup_5; }

		//"wbsActivity"
		public Keyword getWbsActivityKeyword_5_0() { return cWbsActivityKeyword_5_0; }

		//wbsActivity+=[wbs::WBSActivity|QualifiedName]*
		public Assignment getWbsActivityAssignment_5_1() { return cWbsActivityAssignment_5_1; }

		//[wbs::WBSActivity|QualifiedName]
		public CrossReference getWbsActivityWBSActivityCrossReference_5_1_0() { return cWbsActivityWBSActivityCrossReference_5_1_0; }

		//QualifiedName
		public RuleCall getWbsActivityWBSActivityQualifiedNameParserRuleCall_5_1_0_1() { return cWbsActivityWBSActivityQualifiedNameParserRuleCall_5_1_0_1; }

		//ENDLINE
		public RuleCall getENDLINEParserRuleCall_5_2() { return cENDLINEParserRuleCall_5_2; }

		//("dependsOn" dependencies+=[ActivityElement|QualifiedName]* ENDLINE)?
		public Group getGroup_6() { return cGroup_6; }

		//"dependsOn"
		public Keyword getDependsOnKeyword_6_0() { return cDependsOnKeyword_6_0; }

		//dependencies+=[ActivityElement|QualifiedName]*
		public Assignment getDependenciesAssignment_6_1() { return cDependenciesAssignment_6_1; }

		//[ActivityElement|QualifiedName]
		public CrossReference getDependenciesActivityElementCrossReference_6_1_0() { return cDependenciesActivityElementCrossReference_6_1_0; }

		//QualifiedName
		public RuleCall getDependenciesActivityElementQualifiedNameParserRuleCall_6_1_0_1() { return cDependenciesActivityElementQualifiedNameParserRuleCall_6_1_0_1; }

		//ENDLINE
		public RuleCall getENDLINEParserRuleCall_6_2() { return cENDLINEParserRuleCall_6_2; }

		//activities+=ActivityElement*
		public Assignment getActivitiesAssignment_7() { return cActivitiesAssignment_7; }

		//ActivityElement
		public RuleCall getActivitiesActivityElementParserRuleCall_7_0() { return cActivitiesActivityElementParserRuleCall_7_0; }

		////groups += ActivityGroup*
		//CLOSEDCURLY
		public RuleCall getCLOSEDCURLYTerminalRuleCall_8() { return cCLOSEDCURLYTerminalRuleCall_8; }
	}

	public class WBSImportElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "WBSImport");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cWbsKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cImportURIAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cImportURISTRINGTerminalRuleCall_1_0 = (RuleCall)cImportURIAssignment_1.eContents().get(0);
		
		//WBSImport:
		//	"wbs" importURI= // feature must be named importURI
		//	STRING;
		public ParserRule getRule() { return rule; }

		//"wbs" importURI= // feature must be named importURI
		//STRING
		public Group getGroup() { return cGroup; }

		//"wbs"
		public Keyword getWbsKeyword_0() { return cWbsKeyword_0; }

		//importURI= // feature must be named importURI
		//STRING
		public Assignment getImportURIAssignment_1() { return cImportURIAssignment_1; }

		//// feature must be named importURI
		//STRING
		public RuleCall getImportURISTRINGTerminalRuleCall_1_0() { return cImportURISTRINGTerminalRuleCall_1_0; }
	}

	public class ResourcesImportElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ResourcesImport");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cResourcesKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cImportURIAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cImportURISTRINGTerminalRuleCall_1_0 = (RuleCall)cImportURIAssignment_1.eContents().get(0);
		
		//ResourcesImport:
		//	"resources" importURI= // feature must be named importURI
		//	STRING;
		public ParserRule getRule() { return rule; }

		//"resources" importURI= // feature must be named importURI
		//STRING
		public Group getGroup() { return cGroup; }

		//"resources"
		public Keyword getResourcesKeyword_0() { return cResourcesKeyword_0; }

		//importURI= // feature must be named importURI
		//STRING
		public Assignment getImportURIAssignment_1() { return cImportURIAssignment_1; }

		//// feature must be named importURI
		//STRING
		public RuleCall getImportURISTRINGTerminalRuleCall_1_0() { return cImportURISTRINGTerminalRuleCall_1_0; }
	}

	public class PlanImportElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "PlanImport");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPlanKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cImportURIAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cImportURISTRINGTerminalRuleCall_1_0 = (RuleCall)cImportURIAssignment_1.eContents().get(0);
		
		//PlanImport:
		//	"plan" importURI= // feature must be named importURI
		//	STRING;
		public ParserRule getRule() { return rule; }

		//"plan" importURI= // feature must be named importURI
		//STRING
		public Group getGroup() { return cGroup; }

		//"plan"
		public Keyword getPlanKeyword_0() { return cPlanKeyword_0; }

		//importURI= // feature must be named importURI
		//STRING
		public Assignment getImportURIAssignment_1() { return cImportURIAssignment_1; }

		//// feature must be named importURI
		//STRING
		public RuleCall getImportURISTRINGTerminalRuleCall_1_0() { return cImportURISTRINGTerminalRuleCall_1_0; }
	}

	public class QualifiedNameElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "QualifiedName");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cIDTerminalRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cFullStopKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1_1 = (RuleCall)cGroup_1.eContents().get(1);
		
		//QualifiedName:
		//	ID ("." ID)*;
		public ParserRule getRule() { return rule; }

		//ID ("." ID)*
		public Group getGroup() { return cGroup; }

		//ID
		public RuleCall getIDTerminalRuleCall_0() { return cIDTerminalRuleCall_0; }

		//("." ID)*
		public Group getGroup_1() { return cGroup_1; }

		//"."
		public Keyword getFullStopKeyword_1_0() { return cFullStopKeyword_1_0; }

		//ID
		public RuleCall getIDTerminalRuleCall_1_1() { return cIDTerminalRuleCall_1_1; }
	}

	public class QualifiedNameWithWildCardElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "QualifiedNameWithWildCard");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cQualifiedNameParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Keyword cFullStopAsteriskKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//QualifiedNameWithWildCard:
		//	QualifiedName ".*"?;
		public ParserRule getRule() { return rule; }

		//QualifiedName ".*"?
		public Group getGroup() { return cGroup; }

		//QualifiedName
		public RuleCall getQualifiedNameParserRuleCall_0() { return cQualifiedNameParserRuleCall_0; }

		//".*"?
		public Keyword getFullStopAsteriskKeyword_1() { return cFullStopAsteriskKeyword_1; }
	}

	public class ActivityElementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ActivityElement");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cActivityParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cCheckPointParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cActivityGroupParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//ActivityElement:
		//	Activity | CheckPoint | ActivityGroup;
		public ParserRule getRule() { return rule; }

		//Activity | CheckPoint | ActivityGroup
		public Alternatives getAlternatives() { return cAlternatives; }

		//Activity
		public RuleCall getActivityParserRuleCall_0() { return cActivityParserRuleCall_0; }

		//CheckPoint
		public RuleCall getCheckPointParserRuleCall_1() { return cCheckPointParserRuleCall_1; }

		//ActivityGroup
		public RuleCall getActivityGroupParserRuleCall_2() { return cActivityGroupParserRuleCall_2; }
	}

	public class ENDLINEElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ENDLINE");
		private final Keyword cSemicolonKeyword = (Keyword)rule.eContents().get(1);
		
		//ENDLINE:
		//	";";
		public ParserRule getRule() { return rule; }

		//";"
		public Keyword getSemicolonKeyword() { return cSemicolonKeyword; }
	}

	public class CheckPointElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "CheckPoint");
		private final UnorderedGroup cUnorderedGroup = (UnorderedGroup)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cUnorderedGroup.eContents().get(0);
		private final Assignment cDescriptionAssignment_0_0 = (Assignment)cGroup_0.eContents().get(0);
		private final RuleCall cDescriptionML_COMMENTTerminalRuleCall_0_0_0 = (RuleCall)cDescriptionAssignment_0_0.eContents().get(0);
		private final Keyword cCheckPointKeyword_0_1 = (Keyword)cGroup_0.eContents().get(1);
		private final Assignment cNameAssignment_0_2 = (Assignment)cGroup_0.eContents().get(2);
		private final RuleCall cNameIDTerminalRuleCall_0_2_0 = (RuleCall)cNameAssignment_0_2.eContents().get(0);
		private final RuleCall cOPENCURLYTerminalRuleCall_0_3 = (RuleCall)cGroup_0.eContents().get(3);
		private final Group cGroup_0_4 = (Group)cGroup_0.eContents().get(4);
		private final Keyword cNameKeyword_0_4_0 = (Keyword)cGroup_0_4.eContents().get(0);
		private final Assignment cLongNameAssignment_0_4_1 = (Assignment)cGroup_0_4.eContents().get(1);
		private final RuleCall cLongNameSTRINGTerminalRuleCall_0_4_1_0 = (RuleCall)cLongNameAssignment_0_4_1.eContents().get(0);
		private final RuleCall cENDLINEParserRuleCall_0_4_2 = (RuleCall)cGroup_0_4.eContents().get(2);
		private final Group cGroup_0_5 = (Group)cGroup_0.eContents().get(5);
		private final Keyword cWbsDeliverableKeyword_0_5_0 = (Keyword)cGroup_0_5.eContents().get(0);
		private final Assignment cWbsDeliverableAssignment_0_5_1 = (Assignment)cGroup_0_5.eContents().get(1);
		private final CrossReference cWbsDeliverableWBSDeliverableCrossReference_0_5_1_0 = (CrossReference)cWbsDeliverableAssignment_0_5_1.eContents().get(0);
		private final RuleCall cWbsDeliverableWBSDeliverableQualifiedNameParserRuleCall_0_5_1_0_1 = (RuleCall)cWbsDeliverableWBSDeliverableCrossReference_0_5_1_0.eContents().get(1);
		private final RuleCall cENDLINEParserRuleCall_0_5_2 = (RuleCall)cGroup_0_5.eContents().get(2);
		private final Group cGroup_1 = (Group)cUnorderedGroup.eContents().get(1);
		private final UnorderedGroup cUnorderedGroup_1_0 = (UnorderedGroup)cGroup_1.eContents().get(0);
		private final Alternatives cAlternatives_1_0_0 = (Alternatives)cUnorderedGroup_1_0.eContents().get(0);
		private final Group cGroup_1_0_0_0 = (Group)cAlternatives_1_0_0.eContents().get(0);
		private final Keyword cDateKeyword_1_0_0_0_0 = (Keyword)cGroup_1_0_0_0.eContents().get(0);
		private final Assignment cEndAssignment_1_0_0_0_1 = (Assignment)cGroup_1_0_0_0.eContents().get(1);
		private final RuleCall cEndSTRINGTerminalRuleCall_1_0_0_0_1_0 = (RuleCall)cEndAssignment_1_0_0_0_1.eContents().get(0);
		private final RuleCall cENDLINEParserRuleCall_1_0_0_0_2 = (RuleCall)cGroup_1_0_0_0.eContents().get(2);
		private final Group cGroup_1_0_0_1 = (Group)cAlternatives_1_0_0.eContents().get(1);
		private final Keyword cAfterKeyword_1_0_0_1_0 = (Keyword)cGroup_1_0_0_1.eContents().get(0);
		private final Assignment cAfterAssignment_1_0_0_1_1 = (Assignment)cGroup_1_0_0_1.eContents().get(1);
		private final CrossReference cAfterActivityElementCrossReference_1_0_0_1_1_0 = (CrossReference)cAfterAssignment_1_0_0_1_1.eContents().get(0);
		private final RuleCall cAfterActivityElementQualifiedNameParserRuleCall_1_0_0_1_1_0_1 = (RuleCall)cAfterActivityElementCrossReference_1_0_0_1_1_0.eContents().get(1);
		private final Keyword cOffsetKeyword_1_0_0_1_2 = (Keyword)cGroup_1_0_0_1.eContents().get(2);
		private final Assignment cOffsetAssignment_1_0_0_1_3 = (Assignment)cGroup_1_0_0_1.eContents().get(3);
		private final RuleCall cOffsetINTTerminalRuleCall_1_0_0_1_3_0 = (RuleCall)cOffsetAssignment_1_0_0_1_3.eContents().get(0);
		private final RuleCall cENDLINEParserRuleCall_1_0_0_1_4 = (RuleCall)cGroup_1_0_0_1.eContents().get(4);
		private final Group cGroup_1_0_1 = (Group)cUnorderedGroup_1_0.eContents().get(1);
		private final Keyword cCompletenessKeyword_1_0_1_0 = (Keyword)cGroup_1_0_1.eContents().get(0);
		private final Assignment cCompletenessAssignment_1_0_1_1 = (Assignment)cGroup_1_0_1.eContents().get(1);
		private final RuleCall cCompletenessINTTerminalRuleCall_1_0_1_1_0 = (RuleCall)cCompletenessAssignment_1_0_1_1.eContents().get(0);
		private final Keyword cPercentSignKeyword_1_0_1_2 = (Keyword)cGroup_1_0_1.eContents().get(2);
		private final RuleCall cENDLINEParserRuleCall_1_0_1_3 = (RuleCall)cGroup_1_0_1.eContents().get(3);
		private final Group cGroup_1_0_1_4 = (Group)cGroup_1_0_1.eContents().get(4);
		private final Keyword cDependsOnKeyword_1_0_1_4_0 = (Keyword)cGroup_1_0_1_4.eContents().get(0);
		private final Assignment cDependenciesAssignment_1_0_1_4_1 = (Assignment)cGroup_1_0_1_4.eContents().get(1);
		private final CrossReference cDependenciesActivityElementCrossReference_1_0_1_4_1_0 = (CrossReference)cDependenciesAssignment_1_0_1_4_1.eContents().get(0);
		private final RuleCall cDependenciesActivityElementQualifiedNameParserRuleCall_1_0_1_4_1_0_1 = (RuleCall)cDependenciesActivityElementCrossReference_1_0_1_4_1_0.eContents().get(1);
		private final RuleCall cENDLINEParserRuleCall_1_0_1_4_2 = (RuleCall)cGroup_1_0_1_4.eContents().get(2);
		private final RuleCall cCLOSEDCURLYTerminalRuleCall_1_1 = (RuleCall)cGroup_1.eContents().get(1);
		
		//CheckPoint:
		//	description=ML_COMMENT? "CheckPoint" name=ID OPENCURLY ("name" longName=STRING ENDLINE)? ("wbsDeliverable"
		//	wbsDeliverable+=[wbs::WBSDeliverable|QualifiedName]* ENDLINE)? & (("date" end=STRING ENDLINE | "after"
		//	after=[ActivityElement|QualifiedName] "offset" offset=INT ENDLINE) & "completeness" completeness=INT "%" ENDLINE
		//	("dependsOn" dependencies+=[ActivityElement|QualifiedName]* ENDLINE)?) CLOSEDCURLY;
		public ParserRule getRule() { return rule; }

		//description=ML_COMMENT? "CheckPoint" name=ID OPENCURLY ("name" longName=STRING ENDLINE)? ("wbsDeliverable"
		//wbsDeliverable+=[wbs::WBSDeliverable|QualifiedName]* ENDLINE)? & (("date" end=STRING ENDLINE | "after"
		//after=[ActivityElement|QualifiedName] "offset" offset=INT ENDLINE) & "completeness" completeness=INT "%" ENDLINE
		//("dependsOn" dependencies+=[ActivityElement|QualifiedName]* ENDLINE)?) CLOSEDCURLY
		public UnorderedGroup getUnorderedGroup() { return cUnorderedGroup; }

		//description=ML_COMMENT? "CheckPoint" name=ID OPENCURLY ("name" longName=STRING ENDLINE)? ("wbsDeliverable"
		//wbsDeliverable+=[wbs::WBSDeliverable|QualifiedName]* ENDLINE)?
		public Group getGroup_0() { return cGroup_0; }

		//description=ML_COMMENT?
		public Assignment getDescriptionAssignment_0_0() { return cDescriptionAssignment_0_0; }

		//ML_COMMENT
		public RuleCall getDescriptionML_COMMENTTerminalRuleCall_0_0_0() { return cDescriptionML_COMMENTTerminalRuleCall_0_0_0; }

		//"CheckPoint"
		public Keyword getCheckPointKeyword_0_1() { return cCheckPointKeyword_0_1; }

		//name=ID
		public Assignment getNameAssignment_0_2() { return cNameAssignment_0_2; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_0_2_0() { return cNameIDTerminalRuleCall_0_2_0; }

		//OPENCURLY
		public RuleCall getOPENCURLYTerminalRuleCall_0_3() { return cOPENCURLYTerminalRuleCall_0_3; }

		//("name" longName=STRING ENDLINE)?
		public Group getGroup_0_4() { return cGroup_0_4; }

		//"name"
		public Keyword getNameKeyword_0_4_0() { return cNameKeyword_0_4_0; }

		//longName=STRING
		public Assignment getLongNameAssignment_0_4_1() { return cLongNameAssignment_0_4_1; }

		//STRING
		public RuleCall getLongNameSTRINGTerminalRuleCall_0_4_1_0() { return cLongNameSTRINGTerminalRuleCall_0_4_1_0; }

		//ENDLINE
		public RuleCall getENDLINEParserRuleCall_0_4_2() { return cENDLINEParserRuleCall_0_4_2; }

		//("wbsDeliverable" wbsDeliverable+=[wbs::WBSDeliverable|QualifiedName]* ENDLINE)?
		public Group getGroup_0_5() { return cGroup_0_5; }

		//"wbsDeliverable"
		public Keyword getWbsDeliverableKeyword_0_5_0() { return cWbsDeliverableKeyword_0_5_0; }

		//wbsDeliverable+=[wbs::WBSDeliverable|QualifiedName]*
		public Assignment getWbsDeliverableAssignment_0_5_1() { return cWbsDeliverableAssignment_0_5_1; }

		//[wbs::WBSDeliverable|QualifiedName]
		public CrossReference getWbsDeliverableWBSDeliverableCrossReference_0_5_1_0() { return cWbsDeliverableWBSDeliverableCrossReference_0_5_1_0; }

		//QualifiedName
		public RuleCall getWbsDeliverableWBSDeliverableQualifiedNameParserRuleCall_0_5_1_0_1() { return cWbsDeliverableWBSDeliverableQualifiedNameParserRuleCall_0_5_1_0_1; }

		//ENDLINE
		public RuleCall getENDLINEParserRuleCall_0_5_2() { return cENDLINEParserRuleCall_0_5_2; }

		//(("date" end=STRING ENDLINE | "after" after=[ActivityElement|QualifiedName] "offset" offset=INT ENDLINE) &
		//"completeness" completeness=INT "%" ENDLINE ("dependsOn" dependencies+=[ActivityElement|QualifiedName]* ENDLINE)?)
		//CLOSEDCURLY
		public Group getGroup_1() { return cGroup_1; }

		//("date" end=STRING ENDLINE | "after" after=[ActivityElement|QualifiedName] "offset" offset=INT ENDLINE) & "completeness"
		//completeness=INT "%" ENDLINE ("dependsOn" dependencies+=[ActivityElement|QualifiedName]* ENDLINE)?
		public UnorderedGroup getUnorderedGroup_1_0() { return cUnorderedGroup_1_0; }

		//"date" end=STRING ENDLINE | "after" after=[ActivityElement|QualifiedName] "offset" offset=INT ENDLINE
		public Alternatives getAlternatives_1_0_0() { return cAlternatives_1_0_0; }

		//"date" end=STRING ENDLINE
		public Group getGroup_1_0_0_0() { return cGroup_1_0_0_0; }

		//"date"
		public Keyword getDateKeyword_1_0_0_0_0() { return cDateKeyword_1_0_0_0_0; }

		//end=STRING
		public Assignment getEndAssignment_1_0_0_0_1() { return cEndAssignment_1_0_0_0_1; }

		//STRING
		public RuleCall getEndSTRINGTerminalRuleCall_1_0_0_0_1_0() { return cEndSTRINGTerminalRuleCall_1_0_0_0_1_0; }

		//ENDLINE
		public RuleCall getENDLINEParserRuleCall_1_0_0_0_2() { return cENDLINEParserRuleCall_1_0_0_0_2; }

		//"after" after=[ActivityElement|QualifiedName] "offset" offset=INT ENDLINE
		public Group getGroup_1_0_0_1() { return cGroup_1_0_0_1; }

		//"after"
		public Keyword getAfterKeyword_1_0_0_1_0() { return cAfterKeyword_1_0_0_1_0; }

		//after=[ActivityElement|QualifiedName]
		public Assignment getAfterAssignment_1_0_0_1_1() { return cAfterAssignment_1_0_0_1_1; }

		//[ActivityElement|QualifiedName]
		public CrossReference getAfterActivityElementCrossReference_1_0_0_1_1_0() { return cAfterActivityElementCrossReference_1_0_0_1_1_0; }

		//QualifiedName
		public RuleCall getAfterActivityElementQualifiedNameParserRuleCall_1_0_0_1_1_0_1() { return cAfterActivityElementQualifiedNameParserRuleCall_1_0_0_1_1_0_1; }

		//"offset"
		public Keyword getOffsetKeyword_1_0_0_1_2() { return cOffsetKeyword_1_0_0_1_2; }

		//offset=INT
		public Assignment getOffsetAssignment_1_0_0_1_3() { return cOffsetAssignment_1_0_0_1_3; }

		//INT
		public RuleCall getOffsetINTTerminalRuleCall_1_0_0_1_3_0() { return cOffsetINTTerminalRuleCall_1_0_0_1_3_0; }

		//ENDLINE
		public RuleCall getENDLINEParserRuleCall_1_0_0_1_4() { return cENDLINEParserRuleCall_1_0_0_1_4; }

		//"completeness" completeness=INT "%" ENDLINE ("dependsOn" dependencies+=[ActivityElement|QualifiedName]* ENDLINE)?
		public Group getGroup_1_0_1() { return cGroup_1_0_1; }

		//"completeness"
		public Keyword getCompletenessKeyword_1_0_1_0() { return cCompletenessKeyword_1_0_1_0; }

		//completeness=INT
		public Assignment getCompletenessAssignment_1_0_1_1() { return cCompletenessAssignment_1_0_1_1; }

		//INT
		public RuleCall getCompletenessINTTerminalRuleCall_1_0_1_1_0() { return cCompletenessINTTerminalRuleCall_1_0_1_1_0; }

		//"%"
		public Keyword getPercentSignKeyword_1_0_1_2() { return cPercentSignKeyword_1_0_1_2; }

		//ENDLINE
		public RuleCall getENDLINEParserRuleCall_1_0_1_3() { return cENDLINEParserRuleCall_1_0_1_3; }

		//("dependsOn" dependencies+=[ActivityElement|QualifiedName]* ENDLINE)?
		public Group getGroup_1_0_1_4() { return cGroup_1_0_1_4; }

		//"dependsOn"
		public Keyword getDependsOnKeyword_1_0_1_4_0() { return cDependsOnKeyword_1_0_1_4_0; }

		//dependencies+=[ActivityElement|QualifiedName]*
		public Assignment getDependenciesAssignment_1_0_1_4_1() { return cDependenciesAssignment_1_0_1_4_1; }

		//[ActivityElement|QualifiedName]
		public CrossReference getDependenciesActivityElementCrossReference_1_0_1_4_1_0() { return cDependenciesActivityElementCrossReference_1_0_1_4_1_0; }

		//QualifiedName
		public RuleCall getDependenciesActivityElementQualifiedNameParserRuleCall_1_0_1_4_1_0_1() { return cDependenciesActivityElementQualifiedNameParserRuleCall_1_0_1_4_1_0_1; }

		//ENDLINE
		public RuleCall getENDLINEParserRuleCall_1_0_1_4_2() { return cENDLINEParserRuleCall_1_0_1_4_2; }

		//CLOSEDCURLY
		public RuleCall getCLOSEDCURLYTerminalRuleCall_1_1() { return cCLOSEDCURLYTerminalRuleCall_1_1; }
	}

	public class ResourceInvolvementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ResourceInvolvement");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cResourceAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final CrossReference cResourceResourceCrossReference_0_0 = (CrossReference)cResourceAssignment_0.eContents().get(0);
		private final RuleCall cResourceResourceIDTerminalRuleCall_0_0_1 = (RuleCall)cResourceResourceCrossReference_0_0.eContents().get(1);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cAtKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cOccupationAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cOccupationINTTerminalRuleCall_1_1_0 = (RuleCall)cOccupationAssignment_1_1.eContents().get(0);
		private final Keyword cPercentSignKeyword_1_2 = (Keyword)cGroup_1.eContents().get(2);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cAsKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cResponsibilityAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cResponsibilityResponsibilityEnumRuleCall_2_1_0 = (RuleCall)cResponsibilityAssignment_2_1.eContents().get(0);
		private final RuleCall cENDLINEParserRuleCall_3 = (RuleCall)cGroup.eContents().get(3);
		
		//ResourceInvolvement:
		//	resource=[res::Resource] ("at" occupation=INT "%")? ("as" responsibility=Responsibility)? ENDLINE;
		public ParserRule getRule() { return rule; }

		//resource=[res::Resource] ("at" occupation=INT "%")? ("as" responsibility=Responsibility)? ENDLINE
		public Group getGroup() { return cGroup; }

		//resource=[res::Resource]
		public Assignment getResourceAssignment_0() { return cResourceAssignment_0; }

		//[res::Resource]
		public CrossReference getResourceResourceCrossReference_0_0() { return cResourceResourceCrossReference_0_0; }

		//ID
		public RuleCall getResourceResourceIDTerminalRuleCall_0_0_1() { return cResourceResourceIDTerminalRuleCall_0_0_1; }

		//("at" occupation=INT "%")?
		public Group getGroup_1() { return cGroup_1; }

		//"at"
		public Keyword getAtKeyword_1_0() { return cAtKeyword_1_0; }

		//occupation=INT
		public Assignment getOccupationAssignment_1_1() { return cOccupationAssignment_1_1; }

		//INT
		public RuleCall getOccupationINTTerminalRuleCall_1_1_0() { return cOccupationINTTerminalRuleCall_1_1_0; }

		//"%"
		public Keyword getPercentSignKeyword_1_2() { return cPercentSignKeyword_1_2; }

		//("as" responsibility=Responsibility)?
		public Group getGroup_2() { return cGroup_2; }

		//"as"
		public Keyword getAsKeyword_2_0() { return cAsKeyword_2_0; }

		//responsibility=Responsibility
		public Assignment getResponsibilityAssignment_2_1() { return cResponsibilityAssignment_2_1; }

		//Responsibility
		public RuleCall getResponsibilityResponsibilityEnumRuleCall_2_1_0() { return cResponsibilityResponsibilityEnumRuleCall_2_1_0; }

		//ENDLINE
		public RuleCall getENDLINEParserRuleCall_3() { return cENDLINEParserRuleCall_3; }
	}

	public class ActivityElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Activity");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cDescriptionAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cDescriptionML_COMMENTTerminalRuleCall_0_0 = (RuleCall)cDescriptionAssignment_0.eContents().get(0);
		private final Keyword cActivityKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameIDTerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final RuleCall cOPENCURLYTerminalRuleCall_3 = (RuleCall)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cNameKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cLongNameAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cLongNameSTRINGTerminalRuleCall_4_1_0 = (RuleCall)cLongNameAssignment_4_1.eContents().get(0);
		private final RuleCall cENDLINEParserRuleCall_4_2 = (RuleCall)cGroup_4.eContents().get(2);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cInvolvesKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final RuleCall cOPENCURLYTerminalRuleCall_5_1 = (RuleCall)cGroup_5.eContents().get(1);
		private final Assignment cInvolvedResourcesAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final RuleCall cInvolvedResourcesResourceInvolvementParserRuleCall_5_2_0 = (RuleCall)cInvolvedResourcesAssignment_5_2.eContents().get(0);
		private final RuleCall cCLOSEDCURLYTerminalRuleCall_5_3 = (RuleCall)cGroup_5.eContents().get(3);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cWbsActivityKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cWbsActivityAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final CrossReference cWbsActivityWBSActivityCrossReference_6_1_0 = (CrossReference)cWbsActivityAssignment_6_1.eContents().get(0);
		private final RuleCall cWbsActivityWBSActivityQualifiedNameParserRuleCall_6_1_0_1 = (RuleCall)cWbsActivityWBSActivityCrossReference_6_1_0.eContents().get(1);
		private final RuleCall cENDLINEParserRuleCall_6_2 = (RuleCall)cGroup_6.eContents().get(2);
		private final UnorderedGroup cUnorderedGroup_7 = (UnorderedGroup)cGroup.eContents().get(7);
		private final Alternatives cAlternatives_7_0 = (Alternatives)cUnorderedGroup_7.eContents().get(0);
		private final Group cGroup_7_0_0 = (Group)cAlternatives_7_0.eContents().get(0);
		private final Keyword cStartsKeyword_7_0_0_0 = (Keyword)cGroup_7_0_0.eContents().get(0);
		private final Assignment cStartAssignment_7_0_0_1 = (Assignment)cGroup_7_0_0.eContents().get(1);
		private final RuleCall cStartSTRINGTerminalRuleCall_7_0_0_1_0 = (RuleCall)cStartAssignment_7_0_0_1.eContents().get(0);
		private final RuleCall cENDLINEParserRuleCall_7_0_0_2 = (RuleCall)cGroup_7_0_0.eContents().get(2);
		private final Group cGroup_7_0_1 = (Group)cAlternatives_7_0.eContents().get(1);
		private final Keyword cAfterKeyword_7_0_1_0 = (Keyword)cGroup_7_0_1.eContents().get(0);
		private final Assignment cAfterAssignment_7_0_1_1 = (Assignment)cGroup_7_0_1.eContents().get(1);
		private final CrossReference cAfterActivityElementCrossReference_7_0_1_1_0 = (CrossReference)cAfterAssignment_7_0_1_1.eContents().get(0);
		private final RuleCall cAfterActivityElementQualifiedNameParserRuleCall_7_0_1_1_0_1 = (RuleCall)cAfterActivityElementCrossReference_7_0_1_1_0.eContents().get(1);
		private final Keyword cOffsetKeyword_7_0_1_2 = (Keyword)cGroup_7_0_1.eContents().get(2);
		private final Assignment cOffsetAssignment_7_0_1_3 = (Assignment)cGroup_7_0_1.eContents().get(3);
		private final RuleCall cOffsetINTTerminalRuleCall_7_0_1_3_0 = (RuleCall)cOffsetAssignment_7_0_1_3.eContents().get(0);
		private final RuleCall cENDLINEParserRuleCall_7_0_1_4 = (RuleCall)cGroup_7_0_1.eContents().get(4);
		private final Group cGroup_7_1 = (Group)cUnorderedGroup_7.eContents().get(1);
		private final Alternatives cAlternatives_7_1_0 = (Alternatives)cGroup_7_1.eContents().get(0);
		private final Group cGroup_7_1_0_0 = (Group)cAlternatives_7_1_0.eContents().get(0);
		private final Keyword cEndsKeyword_7_1_0_0_0 = (Keyword)cGroup_7_1_0_0.eContents().get(0);
		private final Assignment cEndAssignment_7_1_0_0_1 = (Assignment)cGroup_7_1_0_0.eContents().get(1);
		private final RuleCall cEndSTRINGTerminalRuleCall_7_1_0_0_1_0 = (RuleCall)cEndAssignment_7_1_0_0_1.eContents().get(0);
		private final RuleCall cENDLINEParserRuleCall_7_1_0_0_2 = (RuleCall)cGroup_7_1_0_0.eContents().get(2);
		private final Group cGroup_7_1_0_1 = (Group)cAlternatives_7_1_0.eContents().get(1);
		private final Keyword cDurationKeyword_7_1_0_1_0 = (Keyword)cGroup_7_1_0_1.eContents().get(0);
		private final Assignment cDurationAssignment_7_1_0_1_1 = (Assignment)cGroup_7_1_0_1.eContents().get(1);
		private final RuleCall cDurationINTTerminalRuleCall_7_1_0_1_1_0 = (RuleCall)cDurationAssignment_7_1_0_1_1.eContents().get(0);
		private final RuleCall cENDLINEParserRuleCall_7_1_0_1_2 = (RuleCall)cGroup_7_1_0_1.eContents().get(2);
		private final Keyword cCompletenessKeyword_7_1_1 = (Keyword)cGroup_7_1.eContents().get(1);
		private final Assignment cCompletenessAssignment_7_1_2 = (Assignment)cGroup_7_1.eContents().get(2);
		private final RuleCall cCompletenessINTTerminalRuleCall_7_1_2_0 = (RuleCall)cCompletenessAssignment_7_1_2.eContents().get(0);
		private final Keyword cPercentSignKeyword_7_1_3 = (Keyword)cGroup_7_1.eContents().get(3);
		private final RuleCall cENDLINEParserRuleCall_7_1_4 = (RuleCall)cGroup_7_1.eContents().get(4);
		private final Group cGroup_7_2 = (Group)cUnorderedGroup_7.eContents().get(2);
		private final Keyword cDependsOnKeyword_7_2_0 = (Keyword)cGroup_7_2.eContents().get(0);
		private final Assignment cDependenciesAssignment_7_2_1 = (Assignment)cGroup_7_2.eContents().get(1);
		private final CrossReference cDependenciesActivityElementCrossReference_7_2_1_0 = (CrossReference)cDependenciesAssignment_7_2_1.eContents().get(0);
		private final RuleCall cDependenciesActivityElementQualifiedNameParserRuleCall_7_2_1_0_1 = (RuleCall)cDependenciesActivityElementCrossReference_7_2_1_0.eContents().get(1);
		private final RuleCall cENDLINEParserRuleCall_7_2_2 = (RuleCall)cGroup_7_2.eContents().get(2);
		private final RuleCall cCLOSEDCURLYTerminalRuleCall_8 = (RuleCall)cGroup.eContents().get(8);
		
		//Activity:
		//	description=ML_COMMENT? "Activity" name=ID OPENCURLY ("name" longName=STRING ENDLINE)? ("involves" OPENCURLY
		//	involvedResources+=ResourceInvolvement* CLOSEDCURLY)? ("wbsActivity" wbsActivity+=[wbs::WBSActivity|QualifiedName]*
		//	ENDLINE)? (("starts" start=STRING ENDLINE | "after" after=[ActivityElement|QualifiedName] "offset" offset=INT
		//	ENDLINE) & ("ends" end=STRING ENDLINE | "duration" duration=INT ENDLINE) "completeness" completeness=INT "%" ENDLINE
		//	& ("dependsOn" dependencies+=[ActivityElement|QualifiedName]* ENDLINE)?) CLOSEDCURLY;
		public ParserRule getRule() { return rule; }

		//description=ML_COMMENT? "Activity" name=ID OPENCURLY ("name" longName=STRING ENDLINE)? ("involves" OPENCURLY
		//involvedResources+=ResourceInvolvement* CLOSEDCURLY)? ("wbsActivity" wbsActivity+=[wbs::WBSActivity|QualifiedName]*
		//ENDLINE)? (("starts" start=STRING ENDLINE | "after" after=[ActivityElement|QualifiedName] "offset" offset=INT ENDLINE)
		//& ("ends" end=STRING ENDLINE | "duration" duration=INT ENDLINE) "completeness" completeness=INT "%" ENDLINE &
		//("dependsOn" dependencies+=[ActivityElement|QualifiedName]* ENDLINE)?) CLOSEDCURLY
		public Group getGroup() { return cGroup; }

		//description=ML_COMMENT?
		public Assignment getDescriptionAssignment_0() { return cDescriptionAssignment_0; }

		//ML_COMMENT
		public RuleCall getDescriptionML_COMMENTTerminalRuleCall_0_0() { return cDescriptionML_COMMENTTerminalRuleCall_0_0; }

		//"Activity"
		public Keyword getActivityKeyword_1() { return cActivityKeyword_1; }

		//name=ID
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_2_0() { return cNameIDTerminalRuleCall_2_0; }

		//OPENCURLY
		public RuleCall getOPENCURLYTerminalRuleCall_3() { return cOPENCURLYTerminalRuleCall_3; }

		//("name" longName=STRING ENDLINE)?
		public Group getGroup_4() { return cGroup_4; }

		//"name"
		public Keyword getNameKeyword_4_0() { return cNameKeyword_4_0; }

		//longName=STRING
		public Assignment getLongNameAssignment_4_1() { return cLongNameAssignment_4_1; }

		//STRING
		public RuleCall getLongNameSTRINGTerminalRuleCall_4_1_0() { return cLongNameSTRINGTerminalRuleCall_4_1_0; }

		//ENDLINE
		public RuleCall getENDLINEParserRuleCall_4_2() { return cENDLINEParserRuleCall_4_2; }

		//("involves" OPENCURLY involvedResources+=ResourceInvolvement* CLOSEDCURLY)?
		public Group getGroup_5() { return cGroup_5; }

		//"involves"
		public Keyword getInvolvesKeyword_5_0() { return cInvolvesKeyword_5_0; }

		//OPENCURLY
		public RuleCall getOPENCURLYTerminalRuleCall_5_1() { return cOPENCURLYTerminalRuleCall_5_1; }

		//involvedResources+=ResourceInvolvement*
		public Assignment getInvolvedResourcesAssignment_5_2() { return cInvolvedResourcesAssignment_5_2; }

		//ResourceInvolvement
		public RuleCall getInvolvedResourcesResourceInvolvementParserRuleCall_5_2_0() { return cInvolvedResourcesResourceInvolvementParserRuleCall_5_2_0; }

		//CLOSEDCURLY
		public RuleCall getCLOSEDCURLYTerminalRuleCall_5_3() { return cCLOSEDCURLYTerminalRuleCall_5_3; }

		//("wbsActivity" wbsActivity+=[wbs::WBSActivity|QualifiedName]* ENDLINE)?
		public Group getGroup_6() { return cGroup_6; }

		//"wbsActivity"
		public Keyword getWbsActivityKeyword_6_0() { return cWbsActivityKeyword_6_0; }

		//wbsActivity+=[wbs::WBSActivity|QualifiedName]*
		public Assignment getWbsActivityAssignment_6_1() { return cWbsActivityAssignment_6_1; }

		//[wbs::WBSActivity|QualifiedName]
		public CrossReference getWbsActivityWBSActivityCrossReference_6_1_0() { return cWbsActivityWBSActivityCrossReference_6_1_0; }

		//QualifiedName
		public RuleCall getWbsActivityWBSActivityQualifiedNameParserRuleCall_6_1_0_1() { return cWbsActivityWBSActivityQualifiedNameParserRuleCall_6_1_0_1; }

		//ENDLINE
		public RuleCall getENDLINEParserRuleCall_6_2() { return cENDLINEParserRuleCall_6_2; }

		//("starts" start=STRING ENDLINE | "after" after=[ActivityElement|QualifiedName] "offset" offset=INT ENDLINE) & ("ends"
		//end=STRING ENDLINE | "duration" duration=INT ENDLINE) "completeness" completeness=INT "%" ENDLINE & ("dependsOn"
		//dependencies+=[ActivityElement|QualifiedName]* ENDLINE)?
		public UnorderedGroup getUnorderedGroup_7() { return cUnorderedGroup_7; }

		//"starts" start=STRING ENDLINE | "after" after=[ActivityElement|QualifiedName] "offset" offset=INT ENDLINE
		public Alternatives getAlternatives_7_0() { return cAlternatives_7_0; }

		//"starts" start=STRING ENDLINE
		public Group getGroup_7_0_0() { return cGroup_7_0_0; }

		//"starts"
		public Keyword getStartsKeyword_7_0_0_0() { return cStartsKeyword_7_0_0_0; }

		//start=STRING
		public Assignment getStartAssignment_7_0_0_1() { return cStartAssignment_7_0_0_1; }

		//STRING
		public RuleCall getStartSTRINGTerminalRuleCall_7_0_0_1_0() { return cStartSTRINGTerminalRuleCall_7_0_0_1_0; }

		//ENDLINE
		public RuleCall getENDLINEParserRuleCall_7_0_0_2() { return cENDLINEParserRuleCall_7_0_0_2; }

		//"after" after=[ActivityElement|QualifiedName] "offset" offset=INT ENDLINE
		public Group getGroup_7_0_1() { return cGroup_7_0_1; }

		//"after"
		public Keyword getAfterKeyword_7_0_1_0() { return cAfterKeyword_7_0_1_0; }

		//after=[ActivityElement|QualifiedName]
		public Assignment getAfterAssignment_7_0_1_1() { return cAfterAssignment_7_0_1_1; }

		//[ActivityElement|QualifiedName]
		public CrossReference getAfterActivityElementCrossReference_7_0_1_1_0() { return cAfterActivityElementCrossReference_7_0_1_1_0; }

		//QualifiedName
		public RuleCall getAfterActivityElementQualifiedNameParserRuleCall_7_0_1_1_0_1() { return cAfterActivityElementQualifiedNameParserRuleCall_7_0_1_1_0_1; }

		//"offset"
		public Keyword getOffsetKeyword_7_0_1_2() { return cOffsetKeyword_7_0_1_2; }

		//offset=INT
		public Assignment getOffsetAssignment_7_0_1_3() { return cOffsetAssignment_7_0_1_3; }

		//INT
		public RuleCall getOffsetINTTerminalRuleCall_7_0_1_3_0() { return cOffsetINTTerminalRuleCall_7_0_1_3_0; }

		//ENDLINE
		public RuleCall getENDLINEParserRuleCall_7_0_1_4() { return cENDLINEParserRuleCall_7_0_1_4; }

		//("ends" end=STRING ENDLINE | "duration" duration=INT ENDLINE) "completeness" completeness=INT "%" ENDLINE
		public Group getGroup_7_1() { return cGroup_7_1; }

		//"ends" end=STRING ENDLINE | "duration" duration=INT ENDLINE
		public Alternatives getAlternatives_7_1_0() { return cAlternatives_7_1_0; }

		//"ends" end=STRING ENDLINE
		public Group getGroup_7_1_0_0() { return cGroup_7_1_0_0; }

		//"ends"
		public Keyword getEndsKeyword_7_1_0_0_0() { return cEndsKeyword_7_1_0_0_0; }

		//end=STRING
		public Assignment getEndAssignment_7_1_0_0_1() { return cEndAssignment_7_1_0_0_1; }

		//STRING
		public RuleCall getEndSTRINGTerminalRuleCall_7_1_0_0_1_0() { return cEndSTRINGTerminalRuleCall_7_1_0_0_1_0; }

		//ENDLINE
		public RuleCall getENDLINEParserRuleCall_7_1_0_0_2() { return cENDLINEParserRuleCall_7_1_0_0_2; }

		//"duration" duration=INT ENDLINE
		public Group getGroup_7_1_0_1() { return cGroup_7_1_0_1; }

		//"duration"
		public Keyword getDurationKeyword_7_1_0_1_0() { return cDurationKeyword_7_1_0_1_0; }

		//duration=INT
		public Assignment getDurationAssignment_7_1_0_1_1() { return cDurationAssignment_7_1_0_1_1; }

		//INT
		public RuleCall getDurationINTTerminalRuleCall_7_1_0_1_1_0() { return cDurationINTTerminalRuleCall_7_1_0_1_1_0; }

		//ENDLINE
		public RuleCall getENDLINEParserRuleCall_7_1_0_1_2() { return cENDLINEParserRuleCall_7_1_0_1_2; }

		//"completeness"
		public Keyword getCompletenessKeyword_7_1_1() { return cCompletenessKeyword_7_1_1; }

		//completeness=INT
		public Assignment getCompletenessAssignment_7_1_2() { return cCompletenessAssignment_7_1_2; }

		//INT
		public RuleCall getCompletenessINTTerminalRuleCall_7_1_2_0() { return cCompletenessINTTerminalRuleCall_7_1_2_0; }

		//"%"
		public Keyword getPercentSignKeyword_7_1_3() { return cPercentSignKeyword_7_1_3; }

		//ENDLINE
		public RuleCall getENDLINEParserRuleCall_7_1_4() { return cENDLINEParserRuleCall_7_1_4; }

		//("dependsOn" dependencies+=[ActivityElement|QualifiedName]* ENDLINE)?
		public Group getGroup_7_2() { return cGroup_7_2; }

		//"dependsOn"
		public Keyword getDependsOnKeyword_7_2_0() { return cDependsOnKeyword_7_2_0; }

		//dependencies+=[ActivityElement|QualifiedName]*
		public Assignment getDependenciesAssignment_7_2_1() { return cDependenciesAssignment_7_2_1; }

		//[ActivityElement|QualifiedName]
		public CrossReference getDependenciesActivityElementCrossReference_7_2_1_0() { return cDependenciesActivityElementCrossReference_7_2_1_0; }

		//QualifiedName
		public RuleCall getDependenciesActivityElementQualifiedNameParserRuleCall_7_2_1_0_1() { return cDependenciesActivityElementQualifiedNameParserRuleCall_7_2_1_0_1; }

		//ENDLINE
		public RuleCall getENDLINEParserRuleCall_7_2_2() { return cENDLINEParserRuleCall_7_2_2; }

		//CLOSEDCURLY
		public RuleCall getCLOSEDCURLYTerminalRuleCall_8() { return cCLOSEDCURLYTerminalRuleCall_8; }
	}

	public class DateElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Date");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cINTTerminalRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Keyword cSolidusKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final RuleCall cINTTerminalRuleCall_2 = (RuleCall)cGroup.eContents().get(2);
		private final Keyword cSolidusKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final RuleCall cINTTerminalRuleCall_4 = (RuleCall)cGroup.eContents().get(4);
		
		//Date:
		//	INT "/" INT "/" INT;
		public ParserRule getRule() { return rule; }

		//INT "/" INT "/" INT
		public Group getGroup() { return cGroup; }

		//INT
		public RuleCall getINTTerminalRuleCall_0() { return cINTTerminalRuleCall_0; }

		//"/"
		public Keyword getSolidusKeyword_1() { return cSolidusKeyword_1; }

		//INT
		public RuleCall getINTTerminalRuleCall_2() { return cINTTerminalRuleCall_2; }

		//"/"
		public Keyword getSolidusKeyword_3() { return cSolidusKeyword_3; }

		//INT
		public RuleCall getINTTerminalRuleCall_4() { return cINTTerminalRuleCall_4; }
	}
	
	
	public class ResponsibilityElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "Responsibility");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cRESPONSIBLEEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cRESPONSIBLERESPONSIBLEKeyword_0_0 = (Keyword)cRESPONSIBLEEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cACCOUNTABLEEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cACCOUNTABLEACCOUNTABLEKeyword_1_0 = (Keyword)cACCOUNTABLEEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cCONSULTEDEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cCONSULTEDCONSULTEDKeyword_2_0 = (Keyword)cCONSULTEDEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cINFORMEDEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cINFORMEDINFORMEDKeyword_3_0 = (Keyword)cINFORMEDEnumLiteralDeclaration_3.eContents().get(0);
		
		//enum Responsibility:
		//	RESPONSIBLE | ACCOUNTABLE | CONSULTED | INFORMED;
		public EnumRule getRule() { return rule; }

		//RESPONSIBLE | ACCOUNTABLE | CONSULTED | INFORMED
		public Alternatives getAlternatives() { return cAlternatives; }

		//RESPONSIBLE
		public EnumLiteralDeclaration getRESPONSIBLEEnumLiteralDeclaration_0() { return cRESPONSIBLEEnumLiteralDeclaration_0; }

		//"RESPONSIBLE"
		public Keyword getRESPONSIBLERESPONSIBLEKeyword_0_0() { return cRESPONSIBLERESPONSIBLEKeyword_0_0; }

		//ACCOUNTABLE
		public EnumLiteralDeclaration getACCOUNTABLEEnumLiteralDeclaration_1() { return cACCOUNTABLEEnumLiteralDeclaration_1; }

		//"ACCOUNTABLE"
		public Keyword getACCOUNTABLEACCOUNTABLEKeyword_1_0() { return cACCOUNTABLEACCOUNTABLEKeyword_1_0; }

		//CONSULTED
		public EnumLiteralDeclaration getCONSULTEDEnumLiteralDeclaration_2() { return cCONSULTEDEnumLiteralDeclaration_2; }

		//"CONSULTED"
		public Keyword getCONSULTEDCONSULTEDKeyword_2_0() { return cCONSULTEDCONSULTEDKeyword_2_0; }

		//INFORMED
		public EnumLiteralDeclaration getINFORMEDEnumLiteralDeclaration_3() { return cINFORMEDEnumLiteralDeclaration_3; }

		//"INFORMED"
		public Keyword getINFORMEDINFORMEDKeyword_3_0() { return cINFORMEDINFORMEDKeyword_3_0; }
	}
	
	private ProgramElements pProgram;
	private ProjectElements pProject;
	private AssumptionElements pAssumption;
	private ConstraintElements pConstraint;
	private ActivityGroupElements pActivityGroup;
	private WBSImportElements pWBSImport;
	private ResourcesImportElements pResourcesImport;
	private PlanImportElements pPlanImport;
	private QualifiedNameElements pQualifiedName;
	private QualifiedNameWithWildCardElements pQualifiedNameWithWildCard;
	private ActivityElementElements pActivityElement;
	private ENDLINEElements pENDLINE;
	private CheckPointElements pCheckPoint;
	private ResourceInvolvementElements pResourceInvolvement;
	private ActivityElements pActivity;
	private DateElements pDate;
	private TerminalRule tOPENCURLY;
	private TerminalRule tCLOSEDCURLY;
	private ResponsibilityElements unknownRuleResponsibility;
	
	private final Grammar grammar;

	private TerminalsGrammarAccess gaTerminals;

	@Inject
	public PlanGrammarAccess(GrammarProvider grammarProvider,
		TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("com.lowcoupling.mdpm.lng.plan.Plan".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	
	public Grammar getGrammar() {
		return grammar;
	}
	

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Program:
	//	description=ML_COMMENT? ("Program" name=ID OPENCURLY ("name" longName=STRING ENDLINE)? (plans+=PlanImport ENDLINE)*
	//	("project" referencedProjects+=[Project|QualifiedName] ENDLINE)* projects+=Project* CLOSEDCURLY) | projects+=Project;
	public ProgramElements getProgramAccess() {
		return (pProgram != null) ? pProgram : (pProgram = new ProgramElements());
	}
	
	public ParserRule getProgramRule() {
		return getProgramAccess().getRule();
	}

	//Project:
	//	description=ML_COMMENT? "Project" name=ID OPENCURLY ("name" longName=STRING ENDLINE)? (wbs=WBSImport "project"
	//	wbsProject=[wbs::WBSProject|QualifiedName] ENDLINE)? (resources=ResourcesImport ENDLINE)? (plans+=PlanImport
	//	ENDLINE)* ("assumptions" OPENCURLY assumptions+=Assumption* CLOSEDCURLY)? ("constraints" OPENCURLY
	//	constraints+=Constraint* CLOSEDCURLY)? activities+=ActivityElement* CLOSEDCURLY;
	public ProjectElements getProjectAccess() {
		return (pProject != null) ? pProject : (pProject = new ProjectElements());
	}
	
	public ParserRule getProjectRule() {
		return getProjectAccess().getRule();
	}

	//Assumption:
	//	"-" value=STRING ENDLINE;
	public AssumptionElements getAssumptionAccess() {
		return (pAssumption != null) ? pAssumption : (pAssumption = new AssumptionElements());
	}
	
	public ParserRule getAssumptionRule() {
		return getAssumptionAccess().getRule();
	}

	//Constraint:
	//	"-" value=STRING ENDLINE;
	public ConstraintElements getConstraintAccess() {
		return (pConstraint != null) ? pConstraint : (pConstraint = new ConstraintElements());
	}
	
	public ParserRule getConstraintRule() {
		return getConstraintAccess().getRule();
	}

	//ActivityGroup:
	//	description=ML_COMMENT? "Group" name=ID OPENCURLY ("name" longName=STRING ENDLINE)? ("wbsActivity"
	//	wbsActivity+=[wbs::WBSActivity|QualifiedName]* ENDLINE)? ("dependsOn" dependencies+=[ActivityElement|QualifiedName]*
	//	ENDLINE)? activities+=ActivityElement* //groups += ActivityGroup*
	//	CLOSEDCURLY;
	public ActivityGroupElements getActivityGroupAccess() {
		return (pActivityGroup != null) ? pActivityGroup : (pActivityGroup = new ActivityGroupElements());
	}
	
	public ParserRule getActivityGroupRule() {
		return getActivityGroupAccess().getRule();
	}

	//WBSImport:
	//	"wbs" importURI= // feature must be named importURI
	//	STRING;
	public WBSImportElements getWBSImportAccess() {
		return (pWBSImport != null) ? pWBSImport : (pWBSImport = new WBSImportElements());
	}
	
	public ParserRule getWBSImportRule() {
		return getWBSImportAccess().getRule();
	}

	//ResourcesImport:
	//	"resources" importURI= // feature must be named importURI
	//	STRING;
	public ResourcesImportElements getResourcesImportAccess() {
		return (pResourcesImport != null) ? pResourcesImport : (pResourcesImport = new ResourcesImportElements());
	}
	
	public ParserRule getResourcesImportRule() {
		return getResourcesImportAccess().getRule();
	}

	//PlanImport:
	//	"plan" importURI= // feature must be named importURI
	//	STRING;
	public PlanImportElements getPlanImportAccess() {
		return (pPlanImport != null) ? pPlanImport : (pPlanImport = new PlanImportElements());
	}
	
	public ParserRule getPlanImportRule() {
		return getPlanImportAccess().getRule();
	}

	//QualifiedName:
	//	ID ("." ID)*;
	public QualifiedNameElements getQualifiedNameAccess() {
		return (pQualifiedName != null) ? pQualifiedName : (pQualifiedName = new QualifiedNameElements());
	}
	
	public ParserRule getQualifiedNameRule() {
		return getQualifiedNameAccess().getRule();
	}

	//QualifiedNameWithWildCard:
	//	QualifiedName ".*"?;
	public QualifiedNameWithWildCardElements getQualifiedNameWithWildCardAccess() {
		return (pQualifiedNameWithWildCard != null) ? pQualifiedNameWithWildCard : (pQualifiedNameWithWildCard = new QualifiedNameWithWildCardElements());
	}
	
	public ParserRule getQualifiedNameWithWildCardRule() {
		return getQualifiedNameWithWildCardAccess().getRule();
	}

	//ActivityElement:
	//	Activity | CheckPoint | ActivityGroup;
	public ActivityElementElements getActivityElementAccess() {
		return (pActivityElement != null) ? pActivityElement : (pActivityElement = new ActivityElementElements());
	}
	
	public ParserRule getActivityElementRule() {
		return getActivityElementAccess().getRule();
	}

	//ENDLINE:
	//	";";
	public ENDLINEElements getENDLINEAccess() {
		return (pENDLINE != null) ? pENDLINE : (pENDLINE = new ENDLINEElements());
	}
	
	public ParserRule getENDLINERule() {
		return getENDLINEAccess().getRule();
	}

	//CheckPoint:
	//	description=ML_COMMENT? "CheckPoint" name=ID OPENCURLY ("name" longName=STRING ENDLINE)? ("wbsDeliverable"
	//	wbsDeliverable+=[wbs::WBSDeliverable|QualifiedName]* ENDLINE)? & (("date" end=STRING ENDLINE | "after"
	//	after=[ActivityElement|QualifiedName] "offset" offset=INT ENDLINE) & "completeness" completeness=INT "%" ENDLINE
	//	("dependsOn" dependencies+=[ActivityElement|QualifiedName]* ENDLINE)?) CLOSEDCURLY;
	public CheckPointElements getCheckPointAccess() {
		return (pCheckPoint != null) ? pCheckPoint : (pCheckPoint = new CheckPointElements());
	}
	
	public ParserRule getCheckPointRule() {
		return getCheckPointAccess().getRule();
	}

	//ResourceInvolvement:
	//	resource=[res::Resource] ("at" occupation=INT "%")? ("as" responsibility=Responsibility)? ENDLINE;
	public ResourceInvolvementElements getResourceInvolvementAccess() {
		return (pResourceInvolvement != null) ? pResourceInvolvement : (pResourceInvolvement = new ResourceInvolvementElements());
	}
	
	public ParserRule getResourceInvolvementRule() {
		return getResourceInvolvementAccess().getRule();
	}

	//Activity:
	//	description=ML_COMMENT? "Activity" name=ID OPENCURLY ("name" longName=STRING ENDLINE)? ("involves" OPENCURLY
	//	involvedResources+=ResourceInvolvement* CLOSEDCURLY)? ("wbsActivity" wbsActivity+=[wbs::WBSActivity|QualifiedName]*
	//	ENDLINE)? (("starts" start=STRING ENDLINE | "after" after=[ActivityElement|QualifiedName] "offset" offset=INT
	//	ENDLINE) & ("ends" end=STRING ENDLINE | "duration" duration=INT ENDLINE) "completeness" completeness=INT "%" ENDLINE
	//	& ("dependsOn" dependencies+=[ActivityElement|QualifiedName]* ENDLINE)?) CLOSEDCURLY;
	public ActivityElements getActivityAccess() {
		return (pActivity != null) ? pActivity : (pActivity = new ActivityElements());
	}
	
	public ParserRule getActivityRule() {
		return getActivityAccess().getRule();
	}

	//Date:
	//	INT "/" INT "/" INT;
	public DateElements getDateAccess() {
		return (pDate != null) ? pDate : (pDate = new DateElements());
	}
	
	public ParserRule getDateRule() {
		return getDateAccess().getRule();
	}

	//terminal OPENCURLY:
	//	"{";
	public TerminalRule getOPENCURLYRule() {
		return (tOPENCURLY != null) ? tOPENCURLY : (tOPENCURLY = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "OPENCURLY"));
	} 

	//terminal CLOSEDCURLY:
	//	"}";
	public TerminalRule getCLOSEDCURLYRule() {
		return (tCLOSEDCURLY != null) ? tCLOSEDCURLY : (tCLOSEDCURLY = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "CLOSEDCURLY"));
	} 

	//enum Responsibility:
	//	RESPONSIBLE | ACCOUNTABLE | CONSULTED | INFORMED;
	public ResponsibilityElements getResponsibilityAccess() {
		return (unknownRuleResponsibility != null) ? unknownRuleResponsibility : (unknownRuleResponsibility = new ResponsibilityElements());
	}
	
	public EnumRule getResponsibilityRule() {
		return getResponsibilityAccess().getRule();
	}

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	} 

	//terminal INT returns ecore::EInt:
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	} 

	//terminal STRING:
	//	"\"" ("\\" ("b" | "t" | "n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\""))* "\"" | "\'" ("\\" ("b" | "t" |
	//	"n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
