/*
 * generated by Xtext
 */
package com.lowcoupling.mdpm.lng.pbs.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class PBSUiModule extends com.lowcoupling.mdpm.lng.pbs.ui.AbstractPBSUiModule {
	public PBSUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
