/**
 * generated by Xtext
 */
package com.lowcoupling.mdpm.lng.pbs.validation;

import com.lowcoupling.mdpm.lng.pbs.validation.AbstractPBSValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class PBSValidator extends AbstractPBSValidator {
}
