/*
 * generated by Xtext
 */
package com.lowcoupling.mdpm.lng.resources;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ResourcesRuntimeModule extends com.lowcoupling.mdpm.lng.resources.AbstractResourcesRuntimeModule {

}
