/*
 * generated by Xtext
 */
package com.lowcoupling.mdpm.lng.wbs;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class WBSRuntimeModule extends com.lowcoupling.mdpm.lng.wbs.AbstractWBSRuntimeModule {

	
}
