/*
* generated by Xtext
*/
package com.lowcoupling.mdpm.lng.wbs.validation;
 
import java.util.ArrayList;
import java.util.List;

import org.eclipse.emf.ecore.EPackage;

public class AbstractWBSJavaValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(com.lowcoupling.mdpm.lng.wbs.wBS.WBSPackage.eINSTANCE);
		return result;
	}

}
