/*
 * generated by Xtext
 */
package com.lowcoupling.mdpm.lng.resources.ui;
import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ResourcesUiModule extends com.lowcoupling.mdpm.lng.resources.ui.AbstractResourcesUiModule {
	public ResourcesUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
