/*
 * generated by Xtext
 */
package com.lowcoupling.mdpm.lng.plan;



/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class PlanRuntimeModule extends com.lowcoupling.mdpm.lng.plan.AbstractPlanRuntimeModule {

}
