/*
 * generated by Xtext
 */
package com.lowcoupling.mdpm.lng.wbs.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.editor.autoedit.AbstractEditStrategyProvider;

/**
 * Use this class to register components to be used within the IDE.
 */
public class WBSUiModule extends com.lowcoupling.mdpm.lng.wbs.ui.AbstractWBSUiModule {
	public WBSUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	@Override
	public Class<? extends AbstractEditStrategyProvider> bindAbstractEditStrategyProvider() {
		// TODO Auto-generated method stub
		return super.bindAbstractEditStrategyProvider();
	}
}
