/*
 * generated by Xtext
 */
package com.lowcoupling.mdpm.lng.pbs.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;
import com.lowcoupling.mdpm.lng.pbs.ui.internal.PBSActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class PBSExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return PBSActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return PBSActivator.getInstance().getInjector(PBSActivator.COM_LOWCOUPLING_MDPM_LNG_PBS_PBS);
	}
	
}
