/*
 * generated by Xtext
 */
package com.lowcoupling.mdpm.lng.pbs;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class PBSRuntimeModule extends com.lowcoupling.mdpm.lng.pbs.AbstractPBSRuntimeModule {

}
