/*
* generated by Xtext
*/
package com.lowcoupling.mdpm.lng.pbs;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class PBSStandaloneSetup extends PBSStandaloneSetupGenerated{

	public static void doSetup() {
		new PBSStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

