/**
 * generated by Xtext
 */
package com.lowcoupling.mdpm.lng.pbs.ui.contentassist;

import com.lowcoupling.mdpm.lng.pbs.ui.contentassist.AbstractPBSProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class PBSProposalProvider extends AbstractPBSProposalProvider {
}
