/*
* generated by Xtext
*/
package com.lowcoupling.mdpm.lng.wbs.parser.antlr;

import java.io.InputStream;

import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class WBSAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("com/lowcoupling/mdpm/lng/wbs/parser/antlr/internal/InternalWBS.tokens");
	}
}
