/*
* generated by Xtext
*/
package com.lowcoupling.mdpm.lng.wbs.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import com.lowcoupling.mdpm.lng.wbs.services.WBSGrammarAccess;

public class WBSParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private WBSGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_SL_COMMENT");
	}
	
	@Override
	protected com.lowcoupling.mdpm.lng.wbs.parser.antlr.internal.InternalWBSParser createParser(XtextTokenStream stream) {
		return new com.lowcoupling.mdpm.lng.wbs.parser.antlr.internal.InternalWBSParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "WBS";
	}
	
	public WBSGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(WBSGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
