/*
* generated by Xtext
*/
package com.lowcoupling.mdpm.lng.resources.parser.antlr;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;

import com.google.inject.Inject;
import com.lowcoupling.mdpm.lng.resources.services.ResourcesGrammarAccess;

public class ResourcesParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private ResourcesGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected com.lowcoupling.mdpm.lng.resources.parser.antlr.internal.InternalResourcesParser createParser(XtextTokenStream stream) {
		return new com.lowcoupling.mdpm.lng.resources.parser.antlr.internal.InternalResourcesParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Resources";
	}
	
	public ResourcesGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(ResourcesGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
